TRANSIP: TransIP does not support TXT with trailing whitespace (#4832)
```
=== RUN   TestDNSProviders/dnscontrol.nl/28:complex_TXT:TXT_trailing_ws
    helpers_integration_test.go:246:
        Zone update for dnscontrol.nl
        - DELETE foosp.dnscontrol.nl TXT "with spaces" ttl=300
        + CREATE foows1.dnscontrol.nl TXT "trailingws " ttl=300
    helpers_integration_test.go:251: whitespace at the end or start of the content of a record is not allowed: foows1 300 TXT trailingws
--- FAIL: TestDNSProviders (13.10s)
```